# Data generation

In [2]:
# allows us to have visibility on our package without installing it in editing mode
import sys;
if ".." not in sys.path: sys.path.append("..")

import numpy as np

## Generation of SK instances

The instance is generated by first sampling all independent coefficients as $h_i \sim \mathcal{N}(0,1)$ and $J_{ij}\sim \mathcal{N}(0,1)$ for $i<j$. These coefficients are then normalized by the common factor $$\alpha=\sqrt{\frac{n}{\sum_i h_i^2+\sum_{i<j}J_{ij}^2}}.$$ 
The final coefficients are $\widetilde h_i=\alpha h_i$ and $\widetilde J_{ij}=\alpha J_{ij}$. The corresponding Ising energy is $E(s)=-\sum_{i<j}\widetilde J_{ij}s_i s_j-\sum_i \widetilde h_i s_i$, with $s_i\in\{\pm1\}$.

This differs from directly sampling independent coefficients as $h_i,J_{ij}\sim \mathcal{N}(0,\frac{2}{n+1})$. The similarity is that the normalized ensemble has the same marginal variance, namely 
$$\operatorname{Var}(\widetilde h_i)=\operatorname{Var}(\widetilde J_{ij})=\frac{n}{n+n(n-1)/2}=\frac{2}{n+1}.$$ 
Thus each coefficient still has the SK-type scaling $\widetilde h_i,\widetilde J_{ij}=O(n^{-1/2})$. The difference is that the normalized coefficients are not independent: their total squared norm is fixed exactly as $\sum_i \widetilde h_i^2+\sum_{i<j}\widetilde J_{ij}^2=n$. Therefore, this is a spherical ensemble rather than an independent Gaussian ensemble. For large $n$, individual coefficients look close to Gaussian, but finite-$n$ instances have no global norm fluctuations.

Instances can be created manually using IsingModel or generated randomly using the RandomIsingModel class:

In [2]:
from monaqa2.mcmc.model import IsingModel, RandomIsingModel

random_model = RandomIsingModel(n=3, seed=1234)
print(f"Random model h=\n{random_model.h_rescaled}")
print(f"Random model J=\n{random_model.J_rescaled}")

# Static method from_coefficients expects a vector of length n + n(n-1)/2:
# first the n local fields h_i, then the upper-triangular couplings J_ij for i<j.
fixed_model = IsingModel.from_coefficients(
    n=3, 
    coefficients=np.hstack([random_model.h_rescaled, random_model.J_rescaled[np.triu_indices(n=3,k=1)]])
)
print(f"Fixed model h=\n{fixed_model.h_rescaled}")
print(f"Fixed model J=\n{fixed_model.J_rescaled}")

Random model h=
[-0.25689444 -0.46925507  0.09598513]
Random model J=
[[0.         0.03506258 0.40526672]
 [0.03506258 0.         1.59346204]
 [0.40526672 1.59346204 0.        ]]
Fixed model h=
[-0.25689444 -0.46925507  0.09598513]
Fixed model J=
[[0.         0.03506258 0.40526672]
 [0.03506258 0.         1.59346204]
 [0.40526672 1.59346204 0.        ]]


The instances used are the same one in the work [From quantum-enhanced to quantum-inspired Monte Carlo, Phys. Rev. A 111, 042615](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.111.042615) available here: [https://github.com/petr-ivashkov/quantum-mcmc](https://github.com/petr-ivashkov/quantum-mcmc). These can be loaded using the following utilities.

In [5]:
from monaqa2.data.data import load_instances

In [6]:
n = 3 # between 3 and 10 included
idx = 0 # between 0 and 99 included
loaded_ising_model = load_instances(n, idx)
print(f"Loaded model h=\n{loaded_ising_model.h_rescaled}")
print(f"Loaded model J=\n{loaded_ising_model.J_rescaled}")

Loaded model h=
[-0.3958253  -1.23913116  0.7755628 ]
Loaded model J=
[[ 0.         -0.81979718  0.13006709]
 [-0.81979718  0.          0.13188543]
 [ 0.13006709  0.13188543  0.        ]]


## Best hyperparameters for QEMC trial move

The dataset of instances from [From quantum-enhanced to quantum-inspired Monte Carlo, Phys. Rev. A 111, 042615](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.111.042615) already provide an extensive analysis regarding the hyperparameters $\gamma, t$ of the quantum enhances move working best for each $n$ and instance. These parameters can be loaded with the following:

In [7]:
from monaqa2.data.data import load_best_qemc_gamma_t

load_best_qemc_gamma_t(n, idx)

(np.float64(0.4631578947368421), np.float64(17.23404255319149))

Note that the method `export_best_gamma_t_h5` in the same module allows you to re-generate this file from the cloned repository of Petr's. For details regarding how these parameters are determine, refer to the original publication.  

## Spectral gaps

In [1]:
from monaqa2.data.data import run_experiment_to_generate_spectral_gaps

In [3]:
# Warning! Takes some time and skips results already computed
# (if file spectral_gap.pkl is present, it does nothing)
# run_experiment_to_generate_spectral_gaps()

3 0
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
3 10
3 11
3 12
3 13
3 14
3 15
3 16
3 17
3 18
3 19
3 20
3 21
3 22
3 23
3 24
3 25
3 26
3 27
3 28
3 29
3 30
3 31
3 32
3 33
3 34
3 35
3 36
3 37
3 38
3 39
3 40
3 41
3 42
3 43
3 44
3 45
3 46
3 47
3 48
3 49
3 50
3 51
3 52
3 53
3 54
3 55
3 56
3 57
3 58
3 59
3 60
3 61
3 62
3 63
3 64
3 65
3 66
3 67
3 68
3 69
3 70
3 71
3 72
3 73
3 74
3 75
3 76
3 77
3 78
3 79
3 80
3 81
3 82
3 83
3 84
3 85
3 86
3 87
3 88
3 89
3 90
3 91
3 92
3 93
3 94
3 95
3 96
3 97
3 98
3 99
4 0
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
4 10
4 11
4 12
4 13
4 14
4 15
4 16
4 17
4 18
4 19
4 20
4 21
4 22
4 23
4 24
4 25
4 26
4 27
4 28
4 29
4 30
4 31
4 32
4 33
4 34
4 35
4 36
4 37
4 38
4 39
4 40
4 41
4 42
4 43
4 44
4 45
4 46
4 47
4 48
4 49
4 50
4 51
4 52
4 53
4 54
4 55
4 56
4 57
4 58
4 59
4 60
4 61
4 62
4 63
4 64
4 65
4 66
4 67
4 68
4 69
4 70
4 71
4 72
4 73
4 74
4 75
4 76
4 77
4 78
4 79
4 80
4 81
4 82
4 83
4 84
4 85
4 86
4 87
4 88
4 89
4 90
4 91
4 92
4 93
4 94
4 95
4 96
4 97
4 98
4 99
5 0
5 1
5 2
5 3
5 4


KeyboardInterrupt: 